# Application configs
spring.application.name=codeboxes-server
server.port=8080
spring.main.banner-mode=off

# Database Configs
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DB_NAME}
spring.data.mongodb.auto-index-creation=true

# Redis Configs
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.redis.password=${REDIS_PASSWORD}
spring.redis.ssl.enabled=false

# JWT Configs
jwt.secret=${JWT_SECRET}

# Springdoc Configs
springdoc.swagger-ui.supported-submit-methods=

# Spring Mail Configs
spring.mail.host=smtp.resend.com
spring.mail.port=2587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true